language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: X7bqtUpTfZaPKzus9eeKgOBiIp3aHr+VTaQnT4GWDsQanI8pnTjE+klcB4Jy3NDffRP2ivsXyRjy//BonWNh2v/Nj66q3iiGAaur7rgt9rC9FzzxTX4xyAmCgGTjq5BsaBI+JMWM5Mdx4+Ye3pP4LvtqrvBV2Gq5sXzvch0cA4/4hASXAyLHvUNuEvf+CEJ/dYTcupM7esaE7Awaa2XpV0bkF1X8s1kutaBuCjBlsn5uoZam2k9TRNtrIoGpjj1AcxAsnq+P7IE4e1k1oEYSpFH2rPvLche6QwnuZQ2VHnRIJuz2frusmrxC3lhJXfjJQaFN+eAcRRDzAJE8GHonqkFyVAcdFaRWlABtmRK3k0JTwlW+Yi9e8ZqgTXUVnbx1rbMFvcSgb3IVShrtk4cLhe3PS7iSl+mcQ37+KLTOq1PNvJkxUEmxv8qrrGjis1GoXDnH9axOzqUclnl3xZ1oNEuj44sQggD3wn5lUQJ6eGyY2twrjcObEiV3i7lsAx00CYCO8XG5urRbCJbxE0Tgzyk7fwSvwYa+O/KCiiwRNv5NbL4g35GxbmwRCcFfGXUAWcHaInaXn15yXPbCxnGYapOYbXV4HMdvJHZWvnWV5zpQyarx+JOM98fur7ldLnlYL5zG8Pl9dAuh2OjJzHBsVEPxVP/ien0zECkv9gIMOkE=
  app: character-builder-kim
  skip_cleanup: true
